CREATE DATABASE IF NOT EXITS users;

USE users;

CREATE TABLE Login_1(
	email VARCHAR(120) NOT NULL UNIQUE PRIMARY KEY,
	-- Hashed password
	password VARCHAR(100) NOT NULL
) ENGINE=InnoDB ;

create table Login_2(
	email VARCHAR(120) NOT NULL UNIQUE PRIMARY KEY, 
	-- Hashed passphrase
	passphrase VARCHAR(100) NOT NULL,
	FOREIGN KEY email(email) REFERENCES Login_1(email)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)ENGINE=InnoDB;
